import React, {Suspense} from 'react';
import './globals.css';
import type {Metadata} from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const posts = await fetch(
    `https://hacker-news.firebaseio.com/v0/topstories.json?print=pretty&limitToFirst=10&orderBy="$key"`
  ).then((res) => res.json() as Promise<number[]>);

  const sleep = (ms: number) =>
    new Promise((resolve) => setTimeout(resolve, ms));

  function ListItemLoading() {
    return (
      <li className='my-4 grid h-[64px] items-center px-4'>
        <div role='status' className='max-w-sm animate-pulse'>
          <div className='h-2.5 w-full rounded-full bg-gray-200 dark:bg-gray-700'></div>
          <span className='sr-only'>Loading...</span>
        </div>
        <div className='flex items-center justify-between'>
          <div role='status' className='w-full animate-pulse'>
            <div className='h-2.5 w-12 rounded-full bg-gray-200 dark:bg-gray-700'></div>
            <span className='sr-only'>Loading...</span>
          </div>
          <div role='status' className='w-full animate-pulse'>
            <div className='h-2.5 w-full rounded-full bg-gray-200 dark:bg-gray-700'></div>
            <span className='sr-only'>Loading...</span>
          </div>
        </div>
      </li>
    );
  }
  async function ListItem({id}: {id: number}) {
    await sleep(Math.random() * 3000);

    const post = await fetch(
      `https://hacker-news.firebaseio.com/v0/item/${id}.json?print=pretty`
    ).then(
      (res) => res.json() as Promise<{title: string; by: string; url: string}>
    );
    return (
      <li className='my-4 h-[64px] items-center px-4'>
        <p className='truncate'>{post.title || post.by}</p>
        <div className='mt-2 flex items-center justify-between opacity-50'>
          <p>{post.by}</p>
          <p>Visit website {`>>`}</p>
        </div>
      </li>
    );
  }

  return (
    <html lang='en'>
      <body className='grid h-screen grid-rows-[60px,1fr]'>
        <header className='grid place-content-center bg-yellow-400 font-semibold text-black'>
          Uizard Hackernews Reader
        </header>
        <main className='grid grid-cols-[320px,1fr] gap-4'>
          <aside>
            <ul>
              {posts.map((id) => (
                <Link key={id} href={`/${id}`}>
                  <Suspense fallback={<ListItemLoading />}>
                    <ListItem id={id} />
                  </Suspense>
                </Link>
              ))}
            </ul>
          </aside>
          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
